### ISSUE TITLE
Cannot make a native build using GraalVM 21.3.0

### ISSUE THREAD

**Issue by PierreBtz** [quarkiverse/quarkus-github-api#113]
Hello!

When consuming the extension and trying to build the native image, issues related to the `OkHttpClient` appear:

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: okhttp3.OkHttpClient$Builder. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.kohsuke.github.internal.DefaultGitHubConnector.create(DefaultGitHubConnector.java:45)
Call path from entry point to org.kohsuke.github.internal.DefaultGitHubConnector.create(String):
	no path found from entry point to target method


com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: okhttp3.OkHttpClient$Builder. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.kohsuke.github.internal.DefaultGitHubConnector.create(DefaultGitHubConnector.java:45)
Call path from entry point to org.kohsuke.github.internal.DefaultGitHubConnector.create(String):
	no path found from entry point to target method


	at com.oracle.svm.core.util.UserError.abort(UserError.java:87)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:759)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: okhttp3.OkHttpClient$Builder. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.kohsuke.github.internal.DefaultGitHubConnector.create(DefaultGitHubConnector.java:45)
Call path from entry point to org.kohsuke.github.internal.DefaultGitHubConnector.create(String):
	no path found from entry point to target method


	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:756)
	... 6 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: okhttp3.OkHttpClient$Builder. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:307)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedType(SharedGraphBuilderPhase.java:263)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedNewInstance(SharedGraphBuilderPhase.java:207)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4624)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4617)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5422)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3477)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3437)
```

I managed to reproduce the issue on a minimal project, see repository at https://github.com/PierreBtz/github-api-bug, reproduction steps:

* clone
* build the native image with `mvn package -DskipTests -Pnative` (if you want to run the tests you'll need a github personal access token, see README of the reproduction project).

I compared to what is done for example in the [quarkus-github-app](https://github.com/quarkiverse/quarkus-github-app) but could not find an obvious difference that could explain the issue I'm encountering.

**Comment by PierreBtz** [comment]
For what it's worth, I tried several releases and it seems that 1.131.1 is the last working one for native builds. The first failing one is 1.301.0.

**Comment by gsmet** [comment]
I know what's going on, I fixed it for Quarkus GitHub App but thought I would keep the general behavior as is in the GitHub API one. I'll have a look later today.

**Comment by aheritier** [comment]
Thanks @gsmet 🙇🏻

**Comment by gsmet** [comment]
I'm starting the release process for 1.301.3, I'll let you know when it's on Maven Central.

Important consideration: you shouldn't use OkHttp anymore (short version: Quarkus enforces an old version that is not compatible anymore with how GitHub API uses it). The good news is that the GitHub API has moved to the JDK 11 HTTP Client which works in native too.
So just use the default setup from now on, don't define a specific client and things will work out of the box.

**Comment by PierreBtz** [comment]
Thanks a lot for the fast fix @gsmet !

**Comment by gsmet** [comment]
1.301.3 is available on Maven Central.

Let me know if you have any other issues, I'll be happy to help.

**Comment by PierreBtz** [comment]
@gsmet I confirm the issue is now fixed, thanks a lot!

> Let me know if you have any other issues, I'll be happy to help.

Sure!

**Comment by gsmet** [comment]
@PierreBtz btw, there is another fancy thing in Quarkus GitHub App that is not in the API. If you are using Mockito, you might have issues with the underlying ByteBuddy not targeting the right method when there are bridge methods in the GitHub API (the GitHub API uses them for binary compatibility).
In Quarkus GitHub App, I have something to remove all the bridged methods added for binary compatibility but I haven't put that in the API jar as I wasn't sure people would be happy about it.
If it ends up being an issue for you too, I will move this stuff to the API jar (I might do it anyway at some point as I'm working on a GitHub Action Quarkus extension and I had to duplicate this thing).

**Comment by PierreBtz** [comment]
@gsmet thanks for the hint. At the moment my usage of the api is limited to one method and I didn't see anything suspicious in my tests but I'll keep that in mind.

**Comment by gsmet** [comment]
Yeah, it's really if you are using Mockito + ByteBuddy. If you're not, it's
going to work smoothly.
