### ISSUE TITLE
IllegalAccessError: failed to access class org.kohsuke.github.Previews

### ISSUE THREAD

**Issue by arvidvillen** [quarkiverse/quarkus-github-api#23]
Hi,

I’m aware that this project is not yet released, and I may be doing something wrong but I’m receiving this error when building the native image:

<pre>
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /opt/graalvm/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 -H:ResourceConfigurationFiles=resources-config.json --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar issue-management-cli-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:NativeLinkerOption=-no-pie --no-server -H:-UseServiceLoaderFeature -H:+StackTrace issue-management-cli-1.0.0-SNAPSHOT-runner
[issue-management-cli-1.0.0-SNAPSHOT-runner:198]    classlist:   5,630.42 ms,  1.19 GB
[issue-management-cli-1.0.0-SNAPSHOT-runner:198]        (cap):     655.00 ms,  1.19 GB
[issue-management-cli-1.0.0-SNAPSHOT-runner:198]        setup:   2,933.43 ms,  1.19 GB
[issue-management-cli-1.0.0-SNAPSHOT-runner:198]     analysis:  28,322.61 ms,  2.71 GB
2 fatal errors detected:
Fatal error:com.oracle.svm.core.util.VMError$HostedError: java.lang.reflect.InvocationTargetException
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at com.oracle.svm.hosted.annotation.AnnotationSubstitutionField.readValue(AnnotationSubstitutionField.java:131)
        at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:35)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:99)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:78)
        at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:178)
        at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:346)
        at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:60)
        at com.oracle.graal.pointsto.ObjectScanner$2$1.run(ObjectScanner.java:388)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.oracle.svm.hosted.annotation.AnnotationSubstitutionField.readValue(AnnotationSubstitutionField.java:114)
        ... 14 more
Caused by: java.lang.IllegalAccessError: failed to access class org.kohsuke.github.Previews from class com.sun.proxy.$Proxy309 (org.kohsuke.github.Previews and com.sun.proxy.$Proxy309 are in unnamed module of loader java.net.URLClassLoader @402f32ff)
        at com.sun.proxy.$Proxy309.value(Unknown Source)
        ... 19 more
Fatal error:com.oracle.svm.core.util.VMError$HostedError: java.lang.reflect.InvocationTargetException
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at com.oracle.svm.hosted.annotation.AnnotationSubstitutionField.readValue(AnnotationSubstitutionField.java:131)
        at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:35)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:99)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:78)
        at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:178)
        at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:346)
        at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:60)
        at com.oracle.graal.pointsto.ObjectScanner$2$1.run(ObjectScanner.java:388)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.oracle.svm.hosted.annotation.AnnotationSubstitutionField.readValue(AnnotationSubstitutionField.java:114)
        ... 14 more
Caused by: java.lang.IllegalAccessError: failed to access class org.kohsuke.github.Previews from class com.sun.proxy.$Proxy309 (org.kohsuke.github.Previews and com.sun.proxy.$Proxy309 are in unnamed module of loader java.net.URLClassLoader @402f32ff)
        at com.sun.proxy.$Proxy309.value(Unknown Source)
        ... 19 more
</pre>

Is this something you recognize and know what I’m doing wrong?

**Comment by gsmet** [comment]
Yeah I stumbled upon this error today too. I will investigate this evening.

**Comment by gsmet** [comment]
I just released `0.0.4` that fixes this issue (in fact I just upgraded to latest GitHub API as they fixed the problem there given it was also preventing mocking).

And yes, I should add tests but didn't have the time to do so and don't know when I will. If you want to give it a shot, be my guest :).

**Comment by arvidvillen** [comment]
Works great, thanks for the help!
